n_features: 0 # keep n features per octave, 0 means collect all available keypoints
n_octave_layers: 3
contrast_threshold: 0.04
edge_threshold: 10
sigma: 1.6
descriptor_type: 5 # OpenCV Mat Type, 5 = CV_32F, 0 = CV_8U no other options are supported
enable_percise_upscale: false